### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'tensors'，您好，运行过程中此处报错，请问是什么原因呢？谢谢

### ISSUE THREAD

**Issue by yiseni** [bubbliiiing/detr-pytorch#12]
D:\Python37\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Traceback (most recent call last):
  File "d:/DETR/detr/Argument_test.py", line 14, in <module>
    ys = model(x)
  File "D:\Python37\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\DETR\detr\nets\backbone.py", line 173, in forward
    xs                      = self[0](tensor_list)
  File "D:\Python37\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\DETR\detr\nets\backbone.py", line 141, in forward
    xs                           = self.body(tensor_list.tensors)
AttributeError: 'Tensor' object has no attribute 'tensors'

**Comment by yiseni** [comment]
已解决，感谢

**Comment by LYRgood** [comment]
请问一下是如何解决的？
